### ISSUE TITLE
Usage with AWS Signed Requests?

### ISSUE THREAD

**Issue by chadwilken** [mrkamel/search_flip#12] opened 2020-06-08 15:17 UTC
I'm currently using Searchkick which has support for AWS Signed Requests. I am looking to use a few features from your gem however I cannot seem to get the signed requests to work. Is there a way to hook into the request life-cycle and generate a signed request?

**Comment by mrkamel** [comment] 2020-06-08 19:04
Thanks for opening this. It's possible to hook into the request by providing an http client to the connection:

```ruby
# in an initializer
ESConnection = SearchFlip::Connection.new(base_url: "...", http_client: my_http_client)

# in your index class
class MyIndex
  # ...

  def self.connection
    ESConnection
  end
end
```

The search flip default http client (`SearchFlip::HttpClient`) is not yet capable of the aws signing part, but it's relatively easy to add a `SearchFlip::AwsSigningHttpClient` on top that adds the signed headers before sending the request. I'll try to provide this in the next couple of days.

**Comment by chadwilken** [comment] 2020-06-08 19:09
That would be awesome 👍 . I'll give this a go shortly.

**Comment by chadwilken** [comment] 2020-06-11 19:04
So here is where I landed.

`config/initializers/search_flip.rb`
```ruby
require 'search_flip/aws_signing_http_client'

SearchFlip::Config[:base_url] = ENV['ELASTICSEARCH_URL']

aws_config = SearchFlip::Config[:aws] ||= {}

SearchFlip::Config[:sign_requests] = Rails.application.config.sign_elasticsearch_requests
SearchFlip::Config[:aws][:region] = 'us-east-1'
SearchFlip::Config[:aws][:access_key_id] = Rails.application.credentials.aws[:access_key]
SearchFlip::Config[:aws][:secret_access_key] = Rails.application.credentials.aws[:secret_token]
```

`lib/aws_signing_http_client.rb`
```ruby
# frozen_string_literal: true

require 'http'
require 'aws-sdk-elasticsearchservice'

module SearchFlip
  class AwsSigningHTTPClient
    attr_accessor :request

    def initialize
      self.request = HTTP
    end

    class << self
      extend Forwardable

      def_delegators :new, :headers, :via, :basic_auth, :auth
      def_delegators :new, :get, :post, :put, :delete, :head
    end

    [:headers, :via, :basic_auth, :auth].each do |method|
      define_method method do |*args|
        dup.tap do |client|
          client.request = request.send(method, *args)
        end
      end
    end

    [:get, :post, :put, :delete, :head].each do |method|
      define_method(method) do |url, *args|
        execute(url, method, *args)
      end
    end

    private

      def execute(url, method, *args)
        sig = signature(url, method, args)

        response = request
          .headers(
            'Host' => sig.headers['host'],
            'X-Amz-Date' => sig.headers['x-amz-date'],
            'X-Amz-Security-Token' => sig.headers['x-amz-security-token'],
            'X-Amz-Content-Sha256' => sig.headers['x-amz-content-sha256'],
            'Authorization' => sig.headers['authorization'],
            'Content-Type' => 'application/json'
          )
          .send(method, url, *args)

        raise SearchFlip::ResponseError.new(code: response.code, body: response.body.to_s) unless response.status.success?

        response
      rescue HTTP::ConnectionError => e
        puts e.backtrace.join("\n")
        raise SearchFlip::ConnectionError, e.message
      end

      def signature(url, method, body)
        payload = body.first.presence || {}

        uri = URI.parse(url)
        if payload[:params].present?
          uri.query = URI.encode_www_form(payload[:params].to_a)
        end

        body = payload[:body] || payload[:json]
        unless body.nil? || body.is_a?(String)
          body = SearchFlip::JSON.generate(body)
        end

        self.class.signer.sign_request(
          http_method: method.to_s.upcase,
          url: uri.to_s,
          body: body
        )
      end

      def self.signer
        unless defined? @signer
          config = SearchFlip::Config[:aws]
          @signer ||= Aws::Sigv4::Signer.new(
            service: 'es',
            region: config[:region],
            access_key_id: config[:access_key_id],
            secret_access_key: config[:secret_access_key]
          )
        end
        @signer
      end
  end
end
```

`app/indexes/base_index.rb`
```ruby
class BaseIndex
  include SearchFlip::Index

  def self.connection
    if SearchFlip::Config[:sign_requests]
      ConnectionMutex.synchronize do
        @connection ||= SearchFlip::Connection.new(http_client: SearchFlip::AwsSigningHTTPClient)
      end
    else
      super
    end
  end
end
```

Seems to be working pretty good so far.

**Comment by mrkamel** [comment] 2020-06-11 21:08
thx for sharing :+1: I started to work on it already as well, not finished yet, though.

**Comment by mrkamel** [comment] 2020-06-14 17:20
I decided to take a slightly different approach and added plugin support in `SearchFlip::HTTPClient` plus a `SearchFlip::AwsSigv4Plugin` to support this. I'd be glad if you'd check and try this out. Tried already on a fresh AWS ES instance and everything went smoothly.

**Comment by mrkamel** [comment] 2020-06-14 17:21
branch is `aws_signed_requests`

**Comment by chadwilken** [comment] 2020-06-15 15:04
@mrkamel that did the trick. I like your implementation a lot more as well.

Do I need to synchronize the the `ConnectionMutex` when I override the `connection` method?

**Comment by mrkamel** [comment] 2020-06-15 15:16
> Do I need to synchronize the the `ConnectionMutex` when I override the `connection` method?

... it's a class method with a memoized variable. If two threads use it maybe two connections will be created. However, worst thing that will happen is that  https://github.com/mrkamel/search_flip/blob/master/lib/search_flip/connection.rb#L31 is executed twice. Everything else is thread-safe by design.

What i usually do, is creating a constant `ESConnection = SearchFlip::Connection.new(...)` in an initializer, such that the `connection` method can simply return `ESConnection`.

you can of course also do it within your index class:

```ruby
class MyIndex
  include SearchFlip::Index

  ESConnection = ...

  def self.connection
    ESConnection
  end
```

if you preload your app in dev and prod stages.

**Comment by mrkamel** [comment] 2020-06-18 18:28
merged and released

**Closed by mrkamel** 2020-06-18 18:28 UTC
